//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Employee
{
    public string ID { get; set; }
    public string FullName { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string IdentifyCard { get; set; }
    public string Email { get; set; }
    public string PhoneNumber { get; set; }
    public string EmployeeAddress { get; set; }
    public string DepartmentID { get; set; }
    public string RoleID { get; set; }

    public Employee(string id, string name, string gender, DateTime birthday, string identifyCard, string email, 
        string phoneNumber, string address, string departmentID, string roleID)
    {
        ID = id;
        FullName = name;
        Gender = gender;
        Birthday = birthday;
        IdentifyCard = identifyCard;
        Email = email;
        PhoneNumber = phoneNumber;
        EmployeeAddress = address;
        DepartmentID = departmentID;
        RoleID = roleID; 
    }
}
