//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignment
    {
        public string ProjectID { get; set; }
        public string DepartmentID { get; set; }
    }
}
